name: Deploy content to GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - test-content/**/*
      - .github/workflows/**
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy content to another repository main
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: yhotta240/test-content
          publish_branch: main
          publish_dir: test-content
          enable_jekyll: false
