name: Deploy content to GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - test-content/**/*
      - .github/workflows/**
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Install dependencies
        run: bundle install
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: test-content
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare deploy directory
        run: mkdir deploy-root && mv test-content deploy-root/
      - name: Update artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy-root
      - name: Deploy content to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
